#!/bin/bash

#en
pandoc resume_en.md -o index.html -t html5 \
  -f markdown+smart \
  --standalone \
  --email-obfuscation=references \
  --data-dir=_pandoc \
  --include-in-header=_pandoc/header_styles.html \
  --include-before-body=_pandoc/header_en.html \
  --include-after-body=_pandoc/footer_en.html \
  --variable="pagetitle:Resume :: Mustapha Lateb"

pandoc resume_en.md -o resume_en.odt --reference-doc=_pandoc/reference.odt

libreoffice --headless --convert-to doc resume_en.odt
libreoffice --headless --convert-to pdf resume_en.odt


#fr
pandoc resume_fr.md -o resume_fr.html -t html5 \
  -f markdown+smart \
  --standalone \
  --email-obfuscation=references \
  --data-dir=_pandoc \
  --include-in-header=_pandoc/header_styles.html \
  --include-before-body=_pandoc/header_fr.html \
  --include-after-body=_pandoc/footer_fr.html \
  --variable="pagetitle:Resume :: Mustapha Lateb"

pandoc resume_fr.md -o resume_fr.odt --reference-doc=_pandoc/reference.odt

libreoffice --headless --convert-to doc resume_fr.odt
libreoffice --headless --convert-to pdf resume_fr.odt
