#!/bin/bash

#en
pandoc mlateb_cv_en.md -o index.html -t html5 \
  -f markdown+smart \
  --standalone \
  --email-obfuscation=references \
  --data-dir=_pandoc \
  --include-in-header=_pandoc/header_styles.html \
  --include-before-body=_pandoc/header_en.html \
  --include-after-body=_pandoc/footer_en.html \
  --variable="pagetitle:Resume :: Mustapha Lateb"

pandoc mlateb_cv_en.md -f markdown+smart -o mlateb_cv_en.pdf
pandoc mlateb_cv_en.md -f markdown+smart -o mlateb_cv_en.odt
echo Documents created successfully!!
